services:
  reverseproxy:
    image: nginx:latest
    container_name: reverseproxy
    volumes:
      # Site configs
      - /revpro/conf:/etc/nginx/conf.d:ro
      - /revpro/manconf:/etc/nginx/conf.man:ro
      # Logs
      - /revpro/logs:/revpro/logs
      # Certificates
      - /etc/letsencrypt:/etc/letsencrypt:ro
      # Configuration files /revpro/misc (here written each separately, can be mounted as one folder)
      - /revpro/misc:/etc/nginx/includes
    ports:
      - "80:80"
      - "443:443"
    networks:
      - reverseproxy
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"

  fail2ban:
    image: linuxserver/fail2ban:latest
    container_name: fail2ban
    depends_on:
      - reverseproxy
    volumes:
      - /revpro/logs:/var/log/nginx:ro
      - /data/misc/fail2ban:/config
    environment:
      - TZ=Europe/Prague
    networks:
      - reverseproxy
    restart: unless-stopped

networks:
  reverseproxy:
    external: true
